[project]
name = "gravimory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyxel-utils>=0.1.2",
    "pyxel>=2.2.10",
]

[tool.uv]
dev-dependencies = [
    "pyxel-reload>=0.2.0",
    "ruff>=0.8.5",
]
